CREATE DATABASE IF NOT EXISTS ladybug;

CREATE TABLE IF NOT EXISTS users(
  id INTEGER AUTO_INCREMENT,
  username VARCHAR(16) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);

-- Populate with data
